cleaning exercism test directories
Signed-off-by: Abraham Alamilla <abraham.alamilla@aalamilla.com>

diff --git a/env/functions/test_exercism b/env/functions/test_exercism
--- a/env/functions/test_exercism
+++ b/env/functions/test_exercism
@@ -29,8 +29,15 @@ if [ ! -d "$OUTPUT_DIR" ]; then
   mkdir -p "$OUTPUT_DIR"
 fi
 
-# trap to return to current directory
-trap "cd $CURRENT_DIR" EXIT
+# trap to clean up test runner directory remove test exercise directory and output directory
+# and get back to current directory
+function cleanup {
+  echo "Cleaning up..."
+  rm -rf "$TEST_RUNNER_DIR/$CURRENT_EXERCISE"
+  rm -rf "$OUTPUT_DIR"
+  cd "$CURRENT_DIR"
+}
+trap cleanup EXIT
 
 # change to test runner directory
 echo "Changing to test runner directory..."
